# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10CztpM2zctZapd3GGP8DYsKzmq2l1KmS
"""

!pip install kaggle pandas numpy matplotlib scikit-learn

import os

# Manually set Kaggle credentials
os.environ['KAGGLE_USERNAME'] = "shubhamjenaa"
os.environ['KAGGLE_KEY'] = "KGAT_0d429bcba6b4e6736a8e1b71f6464c26"

!kaggle datasets download -d abhishek14398/salary-dataset-simple-linear-regression

import zipfile

with zipfile.ZipFile("salary-dataset-simple-linear-regression.zip", "r") as zip_ref:
    zip_ref.extractall("salary_data")

!ls

import pandas as pd

df = pd.read_csv("salary_data/Salary_dataset.csv")
df.head()

X = df[['YearsExperience']]
y = df['Salary']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("Model Accuracy (R² Score):", r2)

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

import matplotlib.pyplot as plt

plt.scatter(X_test, y_test, label="Actual")
plt.scatter(X_test, y_pred, label="Predicted")
plt.xlabel("Years of Experience")
plt.ylabel("Salary")
plt.title("Actual vs Predicted Salary")
plt.legend()
plt.show()

plt.scatter(X_train, y_train)
plt.plot(X_train, model.predict(X_train))
plt.xlabel("Years of Experience")
plt.ylabel("Salary")
plt.title("Regression Line")
plt.show()

